// Generated by gencpp from file robot_path_controller/PathResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_PATH_CONTROLLER_MESSAGE_PATHRESPONSE_H
#define ROBOT_PATH_CONTROLLER_MESSAGE_PATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_path_controller
{
template <class ContainerAllocator>
struct PathResponse_
{
  typedef PathResponse_<ContainerAllocator> Type;

  PathResponse_()
    : complete(false)  {
    }
  PathResponse_(const ContainerAllocator& _alloc)
    : complete(false)  {
  (void)_alloc;
    }



   typedef uint8_t _complete_type;
  _complete_type complete;





  typedef boost::shared_ptr< ::robot_path_controller::PathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_path_controller::PathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PathResponse_

typedef ::robot_path_controller::PathResponse_<std::allocator<void> > PathResponse;

typedef boost::shared_ptr< ::robot_path_controller::PathResponse > PathResponsePtr;
typedef boost::shared_ptr< ::robot_path_controller::PathResponse const> PathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_path_controller::PathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_path_controller::PathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_path_controller::PathResponse_<ContainerAllocator1> & lhs, const ::robot_path_controller::PathResponse_<ContainerAllocator2> & rhs)
{
  return lhs.complete == rhs.complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_path_controller::PathResponse_<ContainerAllocator1> & lhs, const ::robot_path_controller::PathResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_path_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_path_controller::PathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_path_controller::PathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_path_controller::PathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_path_controller::PathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_path_controller::PathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_path_controller::PathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_path_controller::PathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d8061d2347621a6ed88451e28811cc7";
  }

  static const char* value(const ::robot_path_controller::PathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d8061d2347621a6ULL;
  static const uint64_t static_value2 = 0xed88451e28811cc7ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_path_controller::PathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_path_controller/PathResponse";
  }

  static const char* value(const ::robot_path_controller::PathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_path_controller::PathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool complete\n"
;
  }

  static const char* value(const ::robot_path_controller::PathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_path_controller::PathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_path_controller::PathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_path_controller::PathResponse_<ContainerAllocator>& v)
  {
    s << indent << "complete: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PATH_CONTROLLER_MESSAGE_PATHRESPONSE_H
