// Generated by gencpp from file robot_path_controller/Path.msg
// DO NOT EDIT!


#ifndef ROBOT_PATH_CONTROLLER_MESSAGE_PATH_H
#define ROBOT_PATH_CONTROLLER_MESSAGE_PATH_H

#include <ros/service_traits.h>


#include <robot_path_controller/PathRequest.h>
#include <robot_path_controller/PathResponse.h>


namespace robot_path_controller
{

struct Path
{

typedef PathRequest Request;
typedef PathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Path
} // namespace robot_path_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_path_controller::Path > {
  static const char* value()
  {
    return "4a214603f798dc39b94ac5b447e437b3";
  }

  static const char* value(const ::robot_path_controller::Path&) { return value(); }
};

template<>
struct DataType< ::robot_path_controller::Path > {
  static const char* value()
  {
    return "robot_path_controller/Path";
  }

  static const char* value(const ::robot_path_controller::Path&) { return value(); }
};


// service_traits::MD5Sum< ::robot_path_controller::PathRequest> should match
// service_traits::MD5Sum< ::robot_path_controller::Path >
template<>
struct MD5Sum< ::robot_path_controller::PathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_path_controller::Path >::value();
  }
  static const char* value(const ::robot_path_controller::PathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_path_controller::PathRequest> should match
// service_traits::DataType< ::robot_path_controller::Path >
template<>
struct DataType< ::robot_path_controller::PathRequest>
{
  static const char* value()
  {
    return DataType< ::robot_path_controller::Path >::value();
  }
  static const char* value(const ::robot_path_controller::PathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_path_controller::PathResponse> should match
// service_traits::MD5Sum< ::robot_path_controller::Path >
template<>
struct MD5Sum< ::robot_path_controller::PathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_path_controller::Path >::value();
  }
  static const char* value(const ::robot_path_controller::PathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_path_controller::PathResponse> should match
// service_traits::DataType< ::robot_path_controller::Path >
template<>
struct DataType< ::robot_path_controller::PathResponse>
{
  static const char* value()
  {
    return DataType< ::robot_path_controller::Path >::value();
  }
  static const char* value(const ::robot_path_controller::PathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_PATH_CONTROLLER_MESSAGE_PATH_H
