// Generated by gencpp from file robot_path_controller/WayPointList.msg
// DO NOT EDIT!


#ifndef ROBOT_PATH_CONTROLLER_MESSAGE_WAYPOINTLIST_H
#define ROBOT_PATH_CONTROLLER_MESSAGE_WAYPOINTLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_path_controller/WayPoint.h>

namespace robot_path_controller
{
template <class ContainerAllocator>
struct WayPointList_
{
  typedef WayPointList_<ContainerAllocator> Type;

  WayPointList_()
    : path()  {
    }
  WayPointList_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robot_path_controller::WayPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robot_path_controller::WayPoint_<ContainerAllocator> >::other >  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::robot_path_controller::WayPointList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_path_controller::WayPointList_<ContainerAllocator> const> ConstPtr;

}; // struct WayPointList_

typedef ::robot_path_controller::WayPointList_<std::allocator<void> > WayPointList;

typedef boost::shared_ptr< ::robot_path_controller::WayPointList > WayPointListPtr;
typedef boost::shared_ptr< ::robot_path_controller::WayPointList const> WayPointListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_path_controller::WayPointList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_path_controller::WayPointList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_path_controller::WayPointList_<ContainerAllocator1> & lhs, const ::robot_path_controller::WayPointList_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_path_controller::WayPointList_<ContainerAllocator1> & lhs, const ::robot_path_controller::WayPointList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_path_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_path_controller::WayPointList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_path_controller::WayPointList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_path_controller::WayPointList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_path_controller::WayPointList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_path_controller::WayPointList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_path_controller::WayPointList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_path_controller::WayPointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6bc47b0184d2e472693eb2c6129282d1";
  }

  static const char* value(const ::robot_path_controller::WayPointList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6bc47b0184d2e472ULL;
  static const uint64_t static_value2 = 0x693eb2c6129282d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_path_controller::WayPointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_path_controller/WayPointList";
  }

  static const char* value(const ::robot_path_controller::WayPointList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_path_controller::WayPointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "WayPoint[] path\n"
"================================================================================\n"
"MSG: robot_path_controller/WayPoint\n"
"float64[2] coord\n"
;
  }

  static const char* value(const ::robot_path_controller::WayPointList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_path_controller::WayPointList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WayPointList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_path_controller::WayPointList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_path_controller::WayPointList_<ContainerAllocator>& v)
  {
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robot_path_controller::WayPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PATH_CONTROLLER_MESSAGE_WAYPOINTLIST_H
